"""Skill ontology used by the RAG retriever and the skill-extraction evaluator.

Each entry is a canonical skill plus alias surface forms. Aliases are matched
case-insensitively at extraction time and used as additional embedding text
so the dense encoder can map varied phrasings ("ml", "machine learning",
"predictive modeling") to the same canonical concept.
"""

from __future__ import annotations

from ..shared import SkillEntry


SKILL_ONTOLOGY: tuple[SkillEntry, ...] = (
    # ---- programming languages ------------------------------------------------
    SkillEntry("python", ("python programming", "python3"), "programming", "General-purpose programming language."),
    SkillEntry("java", ("core java",), "programming", "Java programming language."),
    SkillEntry("javascript", ("js", "ecmascript"), "programming", "JavaScript programming language."),
    SkillEntry("typescript", ("ts",), "programming", "Typed superset of JavaScript."),
    SkillEntry("c++", ("cpp", "c plus plus"), "programming", "Systems programming language."),
    SkillEntry("c#", ("csharp", "c sharp"), "programming", ".NET programming language."),
    SkillEntry("go", ("golang",), "programming", "Go programming language."),
    SkillEntry("rust", (), "programming", "Rust systems programming language."),
    SkillEntry("ruby", (), "programming", "Ruby programming language."),
    SkillEntry("php", (), "programming", "PHP programming language."),
    SkillEntry("scala", (), "programming", "Scala programming language."),
    SkillEntry("kotlin", (), "programming", "Kotlin programming language."),
    SkillEntry("r", ("r programming", "r language"), "programming", "Statistical programming language."),
    SkillEntry("bash", ("shell scripting", "shell"), "programming", "Shell scripting."),
    SkillEntry("sql", ("structured query language",), "data", "Relational query language."),
    # ---- data & ml ------------------------------------------------------------
    SkillEntry("pandas", ("dataframes",), "data", "Tabular data manipulation library."),
    SkillEntry("numpy", ("numerical python",), "data", "Scientific computing library."),
    SkillEntry("scipy", (), "data", "Scientific computing toolkit."),
    SkillEntry("matplotlib", ("plotting",), "data", "Plotting library."),
    SkillEntry("seaborn", (), "data", "Statistical visualization library."),
    SkillEntry("plotly", (), "data", "Interactive visualization library."),
    SkillEntry("scikit-learn", ("sklearn",), "ml", "Classical machine learning toolkit."),
    SkillEntry("tensorflow", ("tf", "keras"), "ml", "Deep learning framework."),
    SkillEntry("pytorch", ("torch",), "ml", "Deep learning framework."),
    SkillEntry("xgboost", ("gradient boosting",), "ml", "Gradient boosted trees."),
    SkillEntry("lightgbm", (), "ml", "Gradient boosted decision trees."),
    SkillEntry("nlp", ("natural language processing",), "ml", "Language modeling and text analytics."),
    SkillEntry("computer vision", ("cv", "image recognition"), "ml", "Visual perception models."),
    SkillEntry("transformers", ("transformer models", "huggingface"), "ml", "Transformer architectures."),
    SkillEntry("llm", ("large language models", "language models"), "ml", "Large language model tooling."),
    SkillEntry("rag", ("retrieval augmented generation",), "ml", "Retrieval-augmented generation."),
    SkillEntry("feature engineering", ("features",), "ml", "Creating predictive features."),
    SkillEntry("statistics", ("statistical analysis",), "analysis", "Inferential and descriptive statistics."),
    SkillEntry("hypothesis testing", ("a/b testing", "ab testing", "experimentation"), "analysis", "Controlled experiments."),
    SkillEntry("regression", ("linear regression", "logistic regression"), "analysis", "Regression modeling."),
    SkillEntry("classification", (), "ml", "Classification modeling."),
    SkillEntry("clustering", ("unsupervised learning",), "analysis", "Unsupervised segmentation."),
    SkillEntry("time series", ("forecasting",), "analysis", "Sequential and forecasting models."),
    SkillEntry("model evaluation", ("metrics", "validation"), "ml", "Model performance analysis."),
    SkillEntry("model deployment", ("mlops",), "ml", "Deploying models to production."),
    SkillEntry("data analysis", (), "analysis", "Exploratory and applied data analysis."),
    SkillEntry("data mining", (), "analysis", "Mining patterns from data at scale."),
    SkillEntry("machine learning", ("ml",), "ml", "Predictive modeling and learning systems."),
    SkillEntry("deep learning", (), "ml", "Neural network modeling."),
    SkillEntry("reinforcement learning", (), "ml", "Reward-driven sequential decision making."),
    # ---- data engineering / databases ---------------------------------------
    SkillEntry("data pipelines", ("etl", "elt", "pipeline"), "data", "Operational data movement and transformation."),
    SkillEntry("data modeling", ("schema design",), "data", "Modeling structured data systems."),
    SkillEntry("apache spark", ("spark",), "data", "Distributed data processing engine."),
    SkillEntry("apache airflow", ("airflow",), "data", "Workflow orchestration."),
    SkillEntry("dbt", (), "data", "Analytics engineering transformations."),
    SkillEntry("kafka", ("streaming",), "data", "Distributed event streaming."),
    SkillEntry("hadoop", ("hdfs",), "data", "Distributed storage and processing."),
    SkillEntry("postgresql", ("postgres",), "data", "Relational database platform."),
    SkillEntry("mysql", (), "data", "Relational database platform."),
    SkillEntry("oracle", (), "data", "Oracle relational database."),
    SkillEntry("mssql", ("sql server", "microsoft sql server"), "data", "SQL Server database."),
    SkillEntry("mongodb", ("nosql", "mongo"), "data", "Document database."),
    SkillEntry("redis", (), "data", "In-memory data store."),
    SkillEntry("snowflake", (), "data", "Cloud data warehouse."),
    SkillEntry("bigquery", (), "data", "Google cloud data warehouse."),
    SkillEntry("redshift", ("amazon redshift",), "data", "AWS data warehouse."),
    # ---- analytics / dashboards ---------------------------------------------
    SkillEntry("dashboarding", ("dashboards", "visualization"), "analytics", "Reporting and decision support."),
    SkillEntry("tableau", (), "analytics", "Analytics dashboarding platform."),
    SkillEntry("power bi", ("powerbi",), "analytics", "Business intelligence and reporting."),
    SkillEntry("looker", ("looker studio",), "analytics", "BI and dashboarding."),
    SkillEntry("excel", ("spreadsheets", "ms excel"), "general", "Spreadsheet analysis."),
    # ---- engineering / devops -----------------------------------------------
    SkillEntry("docker", ("containers",), "engineering", "Containerization platform."),
    SkillEntry("kubernetes", ("k8s",), "engineering", "Container orchestration platform."),
    SkillEntry("terraform", ("infrastructure as code", "iac"), "engineering", "Infrastructure as code."),
    SkillEntry("ansible", (), "engineering", "Configuration management."),
    SkillEntry("cloud", ("cloud computing",), "engineering", "Cloud infrastructure and deployment."),
    SkillEntry("aws", ("amazon web services",), "engineering", "Amazon cloud services."),
    SkillEntry("azure", ("microsoft azure",), "engineering", "Microsoft cloud services."),
    SkillEntry("gcp", ("google cloud", "google cloud platform"), "engineering", "Google cloud services."),
    SkillEntry("apis", ("rest api", "rest apis", "web services", "graphql"), "engineering", "Interface design and integration."),
    SkillEntry("microservices", (), "engineering", "Distributed service architecture."),
    SkillEntry("git", ("version control", "github", "gitlab"), "engineering", "Source control systems."),
    SkillEntry("ci/cd", ("continuous integration", "continuous deployment", "jenkins"), "engineering", "Delivery automation."),
    SkillEntry("testing", ("unit testing", "automated tests", "qa", "quality assurance"), "engineering", "Quality assurance and validation."),
    SkillEntry("react", ("react.js", "reactjs"), "engineering", "Frontend UI library."),
    SkillEntry("angular", ("angularjs",), "engineering", "Frontend framework."),
    SkillEntry("vue", ("vue.js",), "engineering", "Frontend framework."),
    SkillEntry("node.js", ("node", "nodejs"), "engineering", "JavaScript runtime for server-side apps."),
    SkillEntry("flask", (), "engineering", "Lightweight Python web framework."),
    SkillEntry("django", (), "engineering", "Python web framework."),
    SkillEntry("fastapi", (), "engineering", "Modern Python API framework."),
    SkillEntry("spring boot", ("spring",), "engineering", "Java application framework."),
    SkillEntry(".net", ("dotnet", "asp.net"), "engineering", "Microsoft .NET stack."),
    SkillEntry("html", ("html5",), "engineering", "Markup language for the web."),
    SkillEntry("css", ("css3", "sass", "scss"), "engineering", "Styling language for the web."),
    SkillEntry("observability", ("monitoring", "logging", "tracing"), "engineering", "Monitoring and tracing systems."),
    SkillEntry("distributed systems", (), "engineering", "Large-scale distributed architecture."),
    SkillEntry("database optimization", (), "engineering", "Database performance tuning."),
    SkillEntry("system design", (), "engineering", "Architectural design of software systems."),
    SkillEntry("agile", ("scrum", "kanban"), "engineering", "Agile delivery practices."),
    # ---- soft skills --------------------------------------------------------
    SkillEntry("leadership", ("team lead", "leading", "managed", "people management"), "soft", "People and project leadership."),
    SkillEntry("communication", ("written communication", "verbal communication"), "soft", "Written and verbal communication."),
    SkillEntry("stakeholder management", ("client management",), "soft", "Cross-functional alignment and coordination."),
    SkillEntry("project management", ("pmp", "project planning"), "soft", "Planning and execution across stakeholders."),
    SkillEntry("problem solving", ("problem-solving", "critical thinking"), "soft", "Analytical problem solving."),
    SkillEntry("teamwork", ("collaboration",), "soft", "Cross-functional teamwork."),
    SkillEntry("mentoring", ("coaching",), "soft", "Mentoring and coaching teammates."),
    SkillEntry("negotiation", (), "soft", "Negotiation and persuasion."),
    SkillEntry("presentation", ("public speaking", "presentations"), "soft", "Presenting to audiences."),
    SkillEntry("documentation", ("technical writing",), "soft", "Documentation and technical writing."),
    # ---- HR / hiring --------------------------------------------------------
    SkillEntry("recruiting", ("talent acquisition", "hiring", "sourcing"), "hr", "Talent acquisition and hiring operations."),
    SkillEntry("onboarding", ("new hire onboarding",), "hr", "New hire onboarding and enablement."),
    SkillEntry("employee relations", (), "hr", "Employee support and relations."),
    SkillEntry("benefits administration", ("benefits",), "hr", "Benefits operations."),
    SkillEntry("payroll", (), "hr", "Payroll coordination and processing."),
    SkillEntry("compliance", ("regulatory compliance",), "hr", "Policy and regulatory compliance."),
    SkillEntry("hr analytics", (), "hr", "Analytic support for HR operations."),
    SkillEntry("applicant tracking systems", ("ats",), "hr", "Applicant tracking platform workflows."),
    SkillEntry("performance management", ("performance reviews",), "hr", "Performance review and management."),
    SkillEntry("training and development", ("learning and development", "l&d"), "hr", "Training program design."),
    # ---- finance / accounting -----------------------------------------------
    SkillEntry("accounting", ("bookkeeping",), "finance", "Accounting workflows."),
    SkillEntry("auditing", ("internal audit",), "finance", "Audit operations."),
    SkillEntry("financial analysis", ("financial reporting", "financial planning"), "finance", "Financial analysis and reporting."),
    SkillEntry("budgeting", ("forecasting", "budget planning"), "finance", "Budgeting and forecasting."),
    SkillEntry("taxation", ("tax preparation",), "finance", "Tax preparation and compliance."),
    SkillEntry("quickbooks", (), "finance", "Small business accounting software."),
    SkillEntry("sap", ("erp",), "finance", "Enterprise resource planning systems."),
    # ---- sales / marketing --------------------------------------------------
    SkillEntry("sales", ("business development", "b2b sales"), "sales", "Sales operations."),
    SkillEntry("crm", ("salesforce", "hubspot"), "sales", "Customer relationship management."),
    SkillEntry("marketing", ("digital marketing", "content marketing"), "marketing", "Marketing operations."),
    SkillEntry("seo", ("search engine optimization",), "marketing", "Search optimization."),
    SkillEntry("sem", ("paid search", "ppc"), "marketing", "Paid search marketing."),
    SkillEntry("social media", ("social media marketing",), "marketing", "Social media operations."),
    SkillEntry("brand management", ("branding",), "marketing", "Brand strategy and management."),
    # ---- design / creative --------------------------------------------------
    SkillEntry("ui/ux", ("ui design", "ux design", "user experience", "user interface"), "design", "User interface and experience design."),
    SkillEntry("figma", (), "design", "Collaborative design tool."),
    SkillEntry("adobe photoshop", ("photoshop",), "design", "Image editing software."),
    SkillEntry("adobe illustrator", ("illustrator",), "design", "Vector graphics tool."),
    SkillEntry("adobe creative suite", ("adobe creative cloud", "creative suite"), "design", "Adobe design product family."),
    SkillEntry("graphic design", (), "design", "Visual graphic design."),
    SkillEntry("video editing", ("premiere", "final cut"), "design", "Video editing workflows."),
    # ---- domain-specific ----------------------------------------------------
    SkillEntry("teaching", ("instruction", "lesson planning"), "education", "Teaching and instruction."),
    SkillEntry("curriculum design", ("curriculum development",), "education", "Curriculum design."),
    SkillEntry("patient care", (), "healthcare", "Direct patient care."),
    SkillEntry("clinical operations", ("clinical practice",), "healthcare", "Clinical operations."),
    SkillEntry("medical records", ("ehr", "electronic health records"), "healthcare", "Health records administration."),
    SkillEntry("pharmacy", ("pharmacology",), "healthcare", "Pharmacy operations."),
    SkillEntry("legal research", (), "legal", "Legal research."),
    SkillEntry("contract drafting", ("contract review", "contracts"), "legal", "Contract drafting and review."),
    SkillEntry("litigation", (), "legal", "Litigation practice."),
    SkillEntry("construction management", (), "construction", "Construction project oversight."),
    SkillEntry("autocad", ("auto cad",), "engineering", "Computer-aided design software."),
    SkillEntry("food safety", ("haccp",), "operations", "Food safety standards."),
    SkillEntry("inventory management", ("stock management",), "operations", "Inventory operations."),
    SkillEntry("supply chain", ("logistics",), "operations", "Supply chain operations."),
    SkillEntry("customer service", ("customer support",), "operations", "Customer-facing service."),
    SkillEntry("quality control", ("qc",), "operations", "Quality control operations."),
    SkillEntry("research", ("research methodology",), "research", "Research methods."),
    SkillEntry("technical writing", (), "soft", "Writing technical documentation."),
)


def get_default_ontology() -> tuple[SkillEntry, ...]:
    """Return the curated skill ontology."""

    return SKILL_ONTOLOGY
